# Generated by Django 3.1.1 on 2020-10-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_goalkeepers', '0002_auto_20201004_1652'),
        ('teams', '0002_team_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goalie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='floorball_goalkeepers.goalkeeper'),
            preserve_default=False,
        ),
    ]
