# Generated by Django 3.1.1 on 2020-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorballTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('wins', models.PositiveIntegerField()),
                ('loses', models.PositiveIntegerField()),
                ('wins_after_over_time', models.PositiveIntegerField()),
                ('loses_after_over_time', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
            ],
        ),
    ]
