# Generated by Django 3.1.1 on 2020-09-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorballteam',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
