# Generated by Django 3.1.1 on 2020-09-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_teams', '0003_floorballteam_team_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorballteam',
            options={'ordering': ['-points']},
        ),
    ]
