# Generated by Django 3.1.1 on 2020-10-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floorball_teams', '0004_auto_20200928_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goalkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('games_played', models.PositiveIntegerField()),
                ('shoots_on_goal', models.PositiveIntegerField()),
                ('conceded_goals', models.PositiveIntegerField()),
                ('floorball_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalkeepers', to='floorball_teams.floorballteam')),
            ],
        ),
    ]
