# Generated by Django 3.1.1 on 2020-10-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_goalkeepers', '0003_goalkeeper_goalie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalkeeper',
            name='new_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalkeeper',
            name='old_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
