# Generated by Django 3.1.1 on 2020-09-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floorball_teams', '0003_floorballteam_team_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('games_played', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('penalties', models.PositiveIntegerField()),
                ('plus_minus', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floorball_teams.floorballteam')),
            ],
        ),
    ]
