# Generated by Django 3.1.1 on 2020-09-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_teams', '0004_auto_20200928_1257'),
        ('floorball_players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorballplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='floorball_teams.floorballteam'),
        ),
    ]
