# Generated by Django 3.1.1 on 2020-09-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_players', '0002_auto_20200928_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorballplayer',
            old_name='team',
            new_name='floorball_team',
        ),
    ]
