# Generated by Django 3.1.1 on 2020-10-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_players', '0003_auto_20200930_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorballplayer',
            name='new_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floorballplayer',
            name='old_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
