# Generated by Django 3.1.1 on 2020-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_players', '0004_auto_20201006_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorballplayer',
            name='player_url',
            field=models.URLField(default='https://www.ceskyflorbal.cz/osoba/1109291451'),
            preserve_default=False,
        ),
    ]
